### ISSUE TITLE
It does not work perfectly

### ISSUE THREAD

**Issue by hubertfigas** [liderman/php-text-generator#1]
There is a problem, for example:
_echo $textGen->generate("{Good {morning|evening|day}|Goodnight|Hello}, {friend|brother}! {How are you|What's new with you}?");_
return this:
_Goodnight|Hello, brother!_ 

I tried for a longer text and it does not give the expected results.

**Comment by liderman** [comment]
Thank you! Really have a problem. Today I will create fix
